### ISSUE TITLE
ProduceRequest failed: Broker: Not leader for partition: actions Refresh

### ISSUE THREAD

**Issue by sguilly** [Blizzard/node-rdkafka#513]
Sometimes, the producer success to send all messages.

And sometimes, the producer fail to send the first message (and all other)  and i find this in log messages : " ProduceRequest failed: Broker: Not leader for partition: actions Refresh' " with cyclic messages

**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]:  ubuntu 16.04
 - Node Version [e.g. 8.2.1]: 10.10
 - NPM Version [e.g. 5.4.2]: 6.1.0
 - C++ Toolchain : linux g++
 - node-rdkafka version : 2.3.4

**Steps to Reproduce**

Not find logic steps : sometimes works / sometimes fails

**node-rdkafka Configuration Settings**

docker compose 

```
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    environment:
      HOSTNAME_COMMAND: wget -qO- http://ipecho.net/plain ; echo
      KAFKA_LOG_RETENTION_HOURS: '1104'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9098
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_DEFAULT_REPLICATION_FACTOR: '3'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '3'
      JMX_PORT: '1099'
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2182,zk3:2183/kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_MIN_INSYNC_REPLICAS: '2'
      KAFKA_OFFSETS_RETENTION_MINUTES: '66240'
      KAFKA_LISTENERS: OUTSIDE://:9098,PLAINTEXT://:9092
    ports:
     - 9098:9098
```
