### ISSUE TITLE
docker alpine + docker-compose + node-rdkafka: consumer doesn't consume messages 

### ISSUE THREAD

**Issue by nervgh** [Blizzard/node-rdkafka#544]
Hello! 

First of all thanks for the library :+1: 

## My configuration
I have this **docker-compose.yml** configuration

```yml
version: '3.4'
services:

  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.4
    ports:
      - '2181:2181'

  node-notifications:
    image: ${DOCKER_REGISTRY}:development
    environment:
      KAFKA_BROKER_LIST: "PLAINTEXT://kafka:9092"
      KAFKA_TOPIC: 'test2'
    depends_on:
      - kafka
```

this **Dockerfile**

```dockerfile
# The image from Docker Hub
FROM node:8-alpine

# Install librdkafka dependecies
RUN apk add --no-cache bash g++ ca-certificates lz4-dev musl-dev cyrus-sasl-dev openssl-dev make python
RUN apk add --no-cache --virtual .build-deps gcc zlib-dev libc-dev bsd-compat-headers py-setuptools bash

# Set the working directory
WORKDIR /usr/src/app

# Define and set defaults for environment variables
ENV NODE_ENV=development

# Copy package.json & package-lock.json fiels
COPY ["package*.json", "./"]

# Install dependencies and clean up npm's cache
RUN npm ci

# Bundle app sources
COPY ["src", "./src"]

# Make port 8080 available to the world outside this container
EXPOSE 8080

# At the end, set the user to use when running this image
USER node

# Runs when the container launches
CMD ["node", "src/index.js"]
```

and these source code:

## My JS code

**index.js**
```js
// import './producer'
import './consumer'
```

**producer.js**
```js
import * as Kafka from 'node-rdkafka'

const defaultConfig = {
  'metadata.broker.list': process.env.KAFKA_BROKER_LIST,
  'security.protocol': 'plaintext'
}

const producer = new Kafka.Producer(defaultConfig, {})

producer.on('ready', () => {
  console.log('Producer was connected successfully!')

  /*
    Standard API
    https://github.com/Blizzard/node-rdkafka#standard-api
  */
  const response = producer.produce(process.env.KAFKA_TOPIC, -1, Buffer.from('test string '))

  console.log('response', response)

  console.log('Polling...')
  producer.poll()

  console.log('Flushing...')
  producer.flush(100, () => {
    console.log('flush callback')
  })
})

producer.on('event.error', (err) => {
  console.error('Error from producer', err)
})

producer.connect()

//stopping this example after 30s
setTimeout(function() {
  console.log('Timeout is exceeded. Disconnecting...')
  producer.disconnect()
}, 30000)
```

**consumer.js**
```js
import * as Kafka from 'node-rdkafka'

const defaultConfig = {
  // The group.id and metadata.broker.list properties are required for a consumer
  'group.id': 'my-group',
  'metadata.broker.list': process.env.KAFKA_BROKER_LIST,
  'security.protocol': 'plaintext',
  'enable.auto.commit': false
}

const consumer = new Kafka.KafkaConsumer(defaultConfig, {})

consumer.on('ready', () => {
  console.log('Consumer was connected successfully!')

  consumer.subscribe([String(process.env.KAFKA_TOPIC)])
  /*
    Standard API
    https://github.com/Blizzard/node-rdkafka#standard-api-1
  */
  consumer.consume()
})

consumer.on('data', (message: Kafka.ConsumerStreamMessage) => {
  console.log('on:data. Message found: ', message)
  // consumer.commitMessageSync(message)
  consumer.disconnect()
})

consumer.on('event.error', (err) => {
  console.error('Error from consumer')
  console.error(err)
})

consumer.connect()

//stopping this example after 30s
setTimeout(function() {
  console.log('Timeout is exceeded. Disconnecting...')
  consumer.disconnect()
}, 30000)
```

And I have these logs for the producer 
```
Producer was connected successfully!
response true
Polling...
Flushing...
flush callback
Timeout is exceeded. Disconnecting...
```

and the consumer
```
Consumer was connected successfully!
Error from consumer
{ Error: Local: Broker transport failure
  origin: 'local',
  message: 'broker transport failure',
  code: -1,
  errno: -1,
  stack: 'Error: Local: Broker transport failure' }
Error from consumer
{ Error: Local: All broker connections are down
  origin: 'local',
  message: 'all broker connections are down',
  code: -1,
  errno: -1,
  stack: 'Error: Local: All broker connections are down' }
Timeout is exceeded. Disconnecting...
```

## Question
What am I doing wrong? Why my consumer doesn't consume any message?

Thanks!
