### ISSUE TITLE
Problem with building node-rdkafka in container `-std=c++14`

### ISSUE THREAD

**Issue by phracek** [Blizzard/node-rdkafka#910]
**Environment Information**
 - OS [e.g. Mac, Arch, Windows 10]: RHEL7
 - Node Version [e.g. 8.2.1]:  v12.22.5
 - NPM Version [e.g. 5.4.2]: 6.14.14
 - C++ Toolchain [e.g. Visual Studio, llvm, g++]:
 - node-rdkafka version [e.g. 2.3.3]: 1.6.1
 
We are trying to build node-rdkafka in container but it failed with 
```
                out:   TOUCH Release/obj.target/deps/librdkafka.stamp
                out:   CXX(target) Release/obj.target/node-librdkafka/src/binding.o
                out: g++: error: unrecognized command line option '-std=c++14'
                out: make: *** [Release/obj.target/node-librdkafka/src/binding.o] Error 1
                out: rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
                out: make: Leaving directory `/opt/app-root/src/node_modules/node-rdkafka/build'
                out: gyp ERR! build error 
                out: gyp ERR! stack Error: `make` failed with exit code: 2
                out: gyp ERR! stack     at ChildProcess.onExit (/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:194:23)
                out: gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
                out: gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
                out: gyp ERR! System Linux 3.10.0-1160.el7.x86_64
                out: gyp ERR! command "/opt/rh/rh-nodejs12/root/usr/bin/node" "/opt/rh/rh-nodejs12/root/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/bin/node-gyp.js" "rebuild"
                out: gyp ERR! cwd /opt/app-root/src/node_modules/node-rdkafka
                out: gyp ERR! node -v v12.22.5
                out: gyp ERR! node-gyp -v v5.1.0
                out: gyp ERR! not ok 
                out: npm WARN hello-world@0.0.1 No description
                out: npm WARN hello-world@0.0.1 No repository field.
                out: npm WARN hello-world@0.0.1 No license field.
                out: 
                out: npm ERR! code ELIFECYCLE
                out: npm ERR! errno 1
                out: npm ERR! node-rdkafka@2.11.0 install: `node-gyp rebuild`
                out: npm ERR! Exit status 1
```

Configuration summary:
```
                out:   prefix                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
                out:   MKL_DISTRO               rhel
                out:   SOLIB_EXT                .so
                out:   ARCH                     x86_64
                out:   CPU                      generic
                out:   GEN_PKG_CONFIG           y
                out:   libdir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps
                out:   MKL_APP_NAME             librdkafka
                out:   MKL_APP_DESC_ONELINE     The Apache Kafka C/C++ library
                out:   LDFLAGS                  -L/opt/app-root/src/node_modules/node-rdkafka/build/deps
                out:   CC                       gcc
                out:   CXX                      g++
                out:   LD                       ld
                out:   NM                       nm
                out:   OBJDUMP                  objdump
                out:   STRIP                    strip
                out:   RANLIB                   ranlib
                out:   CPPFLAGS                 -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align
                out:   PKG_CONFIG               pkg-config
                out:   INSTALL                  install
                out:   LIB_LDFLAGS              -shared -Wl,-soname,$(LIBFILENAME)
                out:   LDFLAG_LINKERSCRIPT      -Wl,--version-script=
                out:   RDKAFKA_VERSION_STR      1.6.1
                out:   MKL_APP_VERSION          1.6.1
                out:   LIBS                     -lm -lssl -lcrypto   -lcrypto   -lz   -ldl -lpthread -lrt
                out:   MKL_PKGCONFIG_LIBS_PRIVATE -lm -ldl -lpthread -lrt
                out:   MKL_PKGCONFIG_REQUIRES_PRIVATE zlib libcrypto libssl
                out:   CFLAGS                        
                out:   MKL_PKGCONFIG_REQUIRES   zlib libcrypto libssl
                out:   CXXFLAGS                 -Wno-non-virtual-dtor
                out:   SYMDUMPER                $(NM) -D
                out:   MKL_DYNAMIC_LIBS         -lm -lssl -lcrypto -lcrypto -lz -ldl -lpthread -lrt
                out:   exec_prefix              /opt/app-root/src/node_modules/node-rdkafka/build/deps
                out:   bindir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps/bin
                out:   sbindir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/sbin
                out:   libexecdir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/libexec
                out:   datadir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/share
                out:   sysconfdir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/etc
                out:   sharedstatedir           /opt/app-root/src/node_modules/node-rdkafka/build/deps/com
                out:   localstatedir            /opt/app-root/src/node_modules/node-rdkafka/build/deps/var
                out:   runstatedir              /opt/app-root/src/node_modules/node-rdkafka/build/deps/var/run
                out:   includedir               /opt/app-root/src/node_modules/node-rdkafka/build/deps/include
                out:   infodir                  /opt/app-root/src/node_modules/node-rdkafka/build/deps/info
                out:   mandir                   /opt/app-root/src/node_modules/node-rdkafka/build/deps/man
                out:   BUILT_WITH               GCC GXX PKGCONFIG INSTALL GNULD LIBDL PLUGINS ZLIB SSL HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW
```

Any idea? Is the latest `node-rdkafka` already available in `npm` repositories?
